# Generated by Django 4.1.7 on 2023-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, verbose_name="Название")),
                ("about", models.TextField(verbose_name="Описание")),
                ("img", models.ImageField(upload_to="carousel/", verbose_name="Фото")),
                ("urls", models.TextField(verbose_name="Ссылка")),
            ],
        ),
    ]
