# Generated by Django 4.1.7 on 2023-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="Имя пользователя"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="Пароль")),
            ],
        ),
    ]
