# Generated by Django 4.1.7 on 2023-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="img",
            field=models.ImageField(upload_to="media/carousel/", verbose_name="Фото"),
        ),
    ]
