# Generated by Django 4.1.7 on 2023-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_carousel_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="img",
            field=models.ImageField(upload_to="carousel/", verbose_name="Фото"),
        ),
    ]
